### PR TITLE
Add check for man pages and output valid commands

### PR DESCRIPTION
**Pull request by zimka1**
## Changes Description:

Added a check to verify the existence of man pages for each command.
Commands with existing man pages are printed to the screen, while commands without man pages are ignored.

### Loop for command validation:
- In each iteration of the loop, the man page for a command is requested, and the output is saved to a file.
- Errors from the man command are redirected to /dev/null to avoid unnecessary error output when a command doesn’t have a man page.
- If the file contains data (the man page exists), the command is printed to the console.
- A mechanism for clearing the file after each check was added to prevent data accumulation.

### CODE REVIEW

**Comment by williambrach** [comment]
thanks @zimka1 for PR! 

It looks good but what happens in case of not having man page for command (eg. `cd` ) ?

try address this issue and I will merge it + I will add you bonus points.

HINT:
```
if command -v somecommand &> /dev/null; then
    echo "Command exists"
else
    echo "Command does not exist"
fi
```

**Comment by zimka1** [comment]
Added a new commit, now there is an ability to find commands in both man and Bash builtins

**Comment by williambrach** [comment]
@zimka1 can you please address **help** page as I requested in first comment ? 

```bash
if command -v somecommand &> /dev/null; then
    echo "Command exists"
else
    echo "Command does not exist"
fi
```

If you integrate this into your PR it should work.

**Comment by zimka1** [comment]
Sorry, that I didn't do it before, now I hope it works ok

**Comment by williambrach** [comment]
@zimka1  merged. 

thanks your PR.

**Pull request merged**
